# Generated by Django 4.2.3 on 2023-07-07 07:38

import career_map.valid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persion_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('mail_id', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='static/cv', validators=[career_map.valid.validate])),
            ],
        ),
        migrations.CreateModel(
            name='post_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mail_id', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=10000)),
            ],
        ),
    ]
