# Generated by Django 4.2.3 on 2023-07-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_map', '0002_alter_persion_detail_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='job_title',
        ),
        migrations.AddField(
            model_name='post_job',
            name='company_name',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
