# Generated by Django 4.2.3 on 2023-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_map', '0003_jobs_remove_post_job_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persion_detail',
            name='domain',
            field=models.CharField(choices=[('AI', 'AI'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICAL', 'ELECTRICAL')], default='AI', max_length=100, null=True),
        ),
    ]
